# Generated by Django 3.1.7 on 2021-03-18 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='creates_at',
            field=models.DateTimeField(null=True),
        ),
    ]
