# Generated by Django 3.1.7 on 2021-03-19 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='photo',
            field=models.FileField(blank=True, upload_to='post_image'),
        ),
    ]
