# Generated by Django 3.1.7 on 2021-03-19 10:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_item_photo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='photo',
        ),
    ]
