# Generated by Django 3.1.7 on 2021-03-20 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_item_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='department',
        ),
        migrations.AddField(
            model_name='item',
            name='department',
            field=models.ManyToManyField(to='products.Department'),
        ),
    ]
